//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioCatalogo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCatalogo.IServicioCatalogo")]
    public interface IServicioCatalogo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCatalogo/ObtenerCatalogo", ReplyAction="http://tempuri.org/IServicioCatalogo/ObtenerCatalogoResponse")]
        MB.WCF.DataContract.DCCatalogo[] ObtenerCatalogo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCatalogo/ObtenerCatalogo", ReplyAction="http://tempuri.org/IServicioCatalogo/ObtenerCatalogoResponse")]
        System.Threading.Tasks.Task<MB.WCF.DataContract.DCCatalogo[]> ObtenerCatalogoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCatalogoChannel : MB.WEB.ServicioCatalogo.IServicioCatalogo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCatalogoClient : System.ServiceModel.ClientBase<MB.WEB.ServicioCatalogo.IServicioCatalogo>, MB.WEB.ServicioCatalogo.IServicioCatalogo {
        
        public ServicioCatalogoClient() {
        }
        
        public ServicioCatalogoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCatalogoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCatalogoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCatalogoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MB.WCF.DataContract.DCCatalogo[] ObtenerCatalogo() {
            return base.Channel.ObtenerCatalogo();
        }
        
        public System.Threading.Tasks.Task<MB.WCF.DataContract.DCCatalogo[]> ObtenerCatalogoAsync() {
            return base.Channel.ObtenerCatalogoAsync();
        }
    }
}
