//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioPagos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPagos.IServicioPagos")]
    public interface IServicioPagos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPagos/actualizarPago", ReplyAction="http://tempuri.org/IServicioPagos/actualizarPagoResponse")]
        bool actualizarPago(int idCatalogo, System.DateTime fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPagos/actualizarPago", ReplyAction="http://tempuri.org/IServicioPagos/actualizarPagoResponse")]
        System.Threading.Tasks.Task<bool> actualizarPagoAsync(int idCatalogo, System.DateTime fecha);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPagosChannel : MB.WEB.ServicioPagos.IServicioPagos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPagosClient : System.ServiceModel.ClientBase<MB.WEB.ServicioPagos.IServicioPagos>, MB.WEB.ServicioPagos.IServicioPagos {
        
        public ServicioPagosClient() {
        }
        
        public ServicioPagosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPagosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPagosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPagosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool actualizarPago(int idCatalogo, System.DateTime fecha) {
            return base.Channel.actualizarPago(idCatalogo, fecha);
        }
        
        public System.Threading.Tasks.Task<bool> actualizarPagoAsync(int idCatalogo, System.DateTime fecha) {
            return base.Channel.actualizarPagoAsync(idCatalogo, fecha);
        }
    }
}
