//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioIngresos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioIngresos.IServicioIngresos")]
    public interface IServicioIngresos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/registroIngresos", ReplyAction="http://tempuri.org/IServicioIngresos/registroIngresosResponse")]
        bool registroIngresos(MB.WCF.DataContract.DCIngresos dcIngresos, MB.WCF.DataContract.DCHisTipoCambio tipoCambio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/registroIngresos", ReplyAction="http://tempuri.org/IServicioIngresos/registroIngresosResponse")]
        System.Threading.Tasks.Task<bool> registroIngresosAsync(MB.WCF.DataContract.DCIngresos dcIngresos, MB.WCF.DataContract.DCHisTipoCambio tipoCambio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/obtenerUltimoIngreso", ReplyAction="http://tempuri.org/IServicioIngresos/obtenerUltimoIngresoResponse")]
        MB.WCF.DataContract.DCIngresos obtenerUltimoIngreso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/obtenerUltimoIngreso", ReplyAction="http://tempuri.org/IServicioIngresos/obtenerUltimoIngresoResponse")]
        System.Threading.Tasks.Task<MB.WCF.DataContract.DCIngresos> obtenerUltimoIngresoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/eliminarIngresoPorId", ReplyAction="http://tempuri.org/IServicioIngresos/eliminarIngresoPorIdResponse")]
        void eliminarIngresoPorId(int idIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/eliminarIngresoPorId", ReplyAction="http://tempuri.org/IServicioIngresos/eliminarIngresoPorIdResponse")]
        System.Threading.Tasks.Task eliminarIngresoPorIdAsync(int idIngreso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/registroUnionIngreso", ReplyAction="http://tempuri.org/IServicioIngresos/registroUnionIngresoResponse")]
        void registroUnionIngreso(int ingreso, int capital);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/registroUnionIngreso", ReplyAction="http://tempuri.org/IServicioIngresos/registroUnionIngresoResponse")]
        System.Threading.Tasks.Task registroUnionIngresoAsync(int ingreso, int capital);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioIngresosChannel : MB.WEB.ServicioIngresos.IServicioIngresos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioIngresosClient : System.ServiceModel.ClientBase<MB.WEB.ServicioIngresos.IServicioIngresos>, MB.WEB.ServicioIngresos.IServicioIngresos {
        
        public ServicioIngresosClient() {
        }
        
        public ServicioIngresosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioIngresosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioIngresosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioIngresosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool registroIngresos(MB.WCF.DataContract.DCIngresos dcIngresos, MB.WCF.DataContract.DCHisTipoCambio tipoCambio) {
            return base.Channel.registroIngresos(dcIngresos, tipoCambio);
        }
        
        public System.Threading.Tasks.Task<bool> registroIngresosAsync(MB.WCF.DataContract.DCIngresos dcIngresos, MB.WCF.DataContract.DCHisTipoCambio tipoCambio) {
            return base.Channel.registroIngresosAsync(dcIngresos, tipoCambio);
        }
        
        public MB.WCF.DataContract.DCIngresos obtenerUltimoIngreso() {
            return base.Channel.obtenerUltimoIngreso();
        }
        
        public System.Threading.Tasks.Task<MB.WCF.DataContract.DCIngresos> obtenerUltimoIngresoAsync() {
            return base.Channel.obtenerUltimoIngresoAsync();
        }
        
        public void eliminarIngresoPorId(int idIngreso) {
            base.Channel.eliminarIngresoPorId(idIngreso);
        }
        
        public System.Threading.Tasks.Task eliminarIngresoPorIdAsync(int idIngreso) {
            return base.Channel.eliminarIngresoPorIdAsync(idIngreso);
        }
        
        public void registroUnionIngreso(int ingreso, int capital) {
            base.Channel.registroUnionIngreso(ingreso, capital);
        }
        
        public System.Threading.Tasks.Task registroUnionIngresoAsync(int ingreso, int capital) {
            return base.Channel.registroUnionIngresoAsync(ingreso, capital);
        }
    }
}
