//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioIngresos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioIngresos.IServicioIngresos")]
    public interface IServicioIngresos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/registroIngresos", ReplyAction="http://tempuri.org/IServicioIngresos/registroIngresosResponse")]
        void registroIngresos(MB.WCF.DataContract.DCIngresos dcIngresos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioIngresos/registroIngresos", ReplyAction="http://tempuri.org/IServicioIngresos/registroIngresosResponse")]
        System.Threading.Tasks.Task registroIngresosAsync(MB.WCF.DataContract.DCIngresos dcIngresos);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioIngresosChannel : MB.WEB.ServicioIngresos.IServicioIngresos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioIngresosClient : System.ServiceModel.ClientBase<MB.WEB.ServicioIngresos.IServicioIngresos>, MB.WEB.ServicioIngresos.IServicioIngresos {
        
        public ServicioIngresosClient() {
        }
        
        public ServicioIngresosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioIngresosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioIngresosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioIngresosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void registroIngresos(MB.WCF.DataContract.DCIngresos dcIngresos) {
            base.Channel.registroIngresos(dcIngresos);
        }
        
        public System.Threading.Tasks.Task registroIngresosAsync(MB.WCF.DataContract.DCIngresos dcIngresos) {
            return base.Channel.registroIngresosAsync(dcIngresos);
        }
    }
}
