//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioFormaPago {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioFormaPago.IServicioFormaPago")]
    public interface IServicioFormaPago {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFormaPago/obtenerListaFormaPago", ReplyAction="http://tempuri.org/IServicioFormaPago/obtenerListaFormaPagoResponse")]
        MB.WCF.DataContract.DCFormaPago[] obtenerListaFormaPago();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFormaPago/obtenerListaFormaPago", ReplyAction="http://tempuri.org/IServicioFormaPago/obtenerListaFormaPagoResponse")]
        System.Threading.Tasks.Task<MB.WCF.DataContract.DCFormaPago[]> obtenerListaFormaPagoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioFormaPagoChannel : MB.WEB.ServicioFormaPago.IServicioFormaPago, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioFormaPagoClient : System.ServiceModel.ClientBase<MB.WEB.ServicioFormaPago.IServicioFormaPago>, MB.WEB.ServicioFormaPago.IServicioFormaPago {
        
        public ServicioFormaPagoClient() {
        }
        
        public ServicioFormaPagoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioFormaPagoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFormaPagoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioFormaPagoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MB.WCF.DataContract.DCFormaPago[] obtenerListaFormaPago() {
            return base.Channel.obtenerListaFormaPago();
        }
        
        public System.Threading.Tasks.Task<MB.WCF.DataContract.DCFormaPago[]> obtenerListaFormaPagoAsync() {
            return base.Channel.obtenerListaFormaPagoAsync();
        }
    }
}
