//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioMonedas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioMonedas.IServicioMonedas")]
    public interface IServicioMonedas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMonedas/listaMonedas", ReplyAction="http://tempuri.org/IServicioMonedas/listaMonedasResponse")]
        MB.WCF.DataContract.DCMoneda[] listaMonedas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioMonedas/listaMonedas", ReplyAction="http://tempuri.org/IServicioMonedas/listaMonedasResponse")]
        System.Threading.Tasks.Task<MB.WCF.DataContract.DCMoneda[]> listaMonedasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioMonedasChannel : MB.WEB.ServicioMonedas.IServicioMonedas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioMonedasClient : System.ServiceModel.ClientBase<MB.WEB.ServicioMonedas.IServicioMonedas>, MB.WEB.ServicioMonedas.IServicioMonedas {
        
        public ServicioMonedasClient() {
        }
        
        public ServicioMonedasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioMonedasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMonedasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioMonedasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MB.WCF.DataContract.DCMoneda[] listaMonedas() {
            return base.Channel.listaMonedas();
        }
        
        public System.Threading.Tasks.Task<MB.WCF.DataContract.DCMoneda[]> listaMonedasAsync() {
            return base.Channel.listaMonedasAsync();
        }
    }
}
