//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PRESUPUESTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DETALLE_PRESUPUESTO()
        {
            this.T_UNION_DETALLE_PRESUPUESTO = new HashSet<T_UNION_DETALLE_PRESUPUESTO>();
            this.T_UNION_GAS_DET_PRESUP = new HashSet<T_UNION_GAS_DET_PRESUP>();
        }
    
        public int iIdDetalle { get; set; }
        public int iIdCatalogo { get; set; }
        public Nullable<decimal> dMonto { get; set; }
    
        public virtual CATALOGO CATALOGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UNION_DETALLE_PRESUPUESTO> T_UNION_DETALLE_PRESUPUESTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UNION_GAS_DET_PRESUP> T_UNION_GAS_DET_PRESUP { get; set; }
    }
}
