//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GASTOS
    {
        public int iIdGastos { get; set; }
        public int iIdCategoria { get; set; }
        public Nullable<decimal> dMonto { get; set; }
        public Nullable<System.DateTime> dFecha { get; set; }
        public Nullable<int> iIdMoneda { get; set; }
        public string vDetalle { get; set; }
        public Nullable<int> iIdFormaPago { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual MONEDA MONEDA { get; set; }
    }
}
