//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GASTOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GASTOS()
        {
            this.DETALLE_PRESUPUESTO = new HashSet<DETALLE_PRESUPUESTO>();
            this.T_UNION_HIS_CF_IG = new HashSet<T_UNION_HIS_CF_IG>();
        }
    
        public int iIdGastos { get; set; }
        public int iIdCatalogo { get; set; }
        public Nullable<decimal> dMonto { get; set; }
        public Nullable<System.DateTime> dFecha { get; set; }
        public Nullable<int> iIdTipoCambio { get; set; }
        public string vDetalle { get; set; }
        public Nullable<int> iIdFormaPago { get; set; }
    
        public virtual CATALOGO CATALOGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_PRESUPUESTO> DETALLE_PRESUPUESTO { get; set; }
        public virtual FORMA_PAGO FORMA_PAGO { get; set; }
        public virtual HIS_TIPO_CAMBIO HIS_TIPO_CAMBIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UNION_HIS_CF_IG> T_UNION_HIS_CF_IG { get; set; }
    }
}
