//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_CAPITAL_FINANCIERO
    {
        public int iIdCapitalF { get; set; }
        public decimal dMontoCF { get; set; }
        public Nullable<System.DateTime> dFechaDeCorte { get; set; }
        public Nullable<bool> bEstado { get; set; }
    }
}
