//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIS_CAPITAL_FINANCIERO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HIS_CAPITAL_FINANCIERO()
        {
            this.T_UNION_HIS_CF_IG = new HashSet<T_UNION_HIS_CF_IG>();
        }
    
        public int iIdCapitalF { get; set; }
        public Nullable<decimal> dMontoCF { get; set; }
        public Nullable<System.DateTime> dFechaDeCorte { get; set; }
        public Nullable<bool> bEstado { get; set; }
        public Nullable<int> iIdIngreso { get; set; }
        public Nullable<int> iIdGastos { get; set; }
    
        public virtual GASTOS GASTOS { get; set; }
        public virtual INGRESOS INGRESOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UNION_HIS_CF_IG> T_UNION_HIS_CF_IG { get; set; }
    }
}
