//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESOS
    {
        public int iIdIngreso { get; set; }
        public decimal dMonto { get; set; }
        public System.DateTime dFecha { get; set; }
        public string vConcepto { get; set; }
        public Nullable<int> iMoneda { get; set; }
    
        public virtual MONEDA MONEDA { get; set; }
    }
}
