//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class INGRESOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public INGRESOS()
        {
            this.T_UNION_HIS_CF_IG = new HashSet<T_UNION_HIS_CF_IG>();
        }
    
        public int iIdIngreso { get; set; }
        public decimal dMonto { get; set; }
        public System.DateTime dFecha { get; set; }
        public string vConcepto { get; set; }
        public Nullable<int> iIdTipoCambio { get; set; }
    
        public virtual HIS_TIPO_CAMBIO HIS_TIPO_CAMBIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UNION_HIS_CF_IG> T_UNION_HIS_CF_IG { get; set; }
    }
}
