//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MBEntities2 : DbContext
    {
        public MBEntities2()
            : base("name=MBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATALOGO> CATALOGO { get; set; }
        public virtual DbSet<DETALLE_PRESUPUESTO> DETALLE_PRESUPUESTO { get; set; }
        public virtual DbSet<FORMA_PAGO> FORMA_PAGO { get; set; }
        public virtual DbSet<GASTOS> GASTOS { get; set; }
        public virtual DbSet<HIS_CAPITAL_FINANCIERO> HIS_CAPITAL_FINANCIERO { get; set; }
        public virtual DbSet<HIS_TIPO_CAMBIO> HIS_TIPO_CAMBIO { get; set; }
        public virtual DbSet<INGRESOS> INGRESOS { get; set; }
        public virtual DbSet<MONEDA> MONEDA { get; set; }
        public virtual DbSet<PAGOS> PAGOS { get; set; }
        public virtual DbSet<PRESUPUESTO> PRESUPUESTO { get; set; }
        public virtual DbSet<T_UNION_DETALLE_PRESUPUESTO> T_UNION_DETALLE_PRESUPUESTO { get; set; }
        public virtual DbSet<T_UNION_HIS_CF_IG> T_UNION_HIS_CF_IG { get; set; }
    }
}
