//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS
    {
        public int iIdPagos { get; set; }
        public Nullable<System.DateTime> dFechaVencePago { get; set; }
        public Nullable<decimal> dMonto { get; set; }
        public Nullable<bool> bEstado { get; set; }
        public Nullable<int> iIdCatalogo { get; set; }
    
        public virtual CATALOGO CATALOGO { get; set; }
    }
}
