//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS
    {
        public int iIdPagos { get; set; }
        public string vConcepto { get; set; }
        public Nullable<System.DateTime> dFechaVencePago { get; set; }
        public Nullable<decimal> dMonto { get; set; }
        public Nullable<bool> bEstado { get; set; }
        public Nullable<int> iIdCategoria { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
    }
}
