//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WCF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESUPUESTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESUPUESTO()
        {
            this.T_UNION_DETALLE_PRESUPUESTO = new HashSet<T_UNION_DETALLE_PRESUPUESTO>();
        }
    
        public int iIdPresupuesto { get; set; }
        public Nullable<System.DateTime> dFechaInicio { get; set; }
        public Nullable<System.DateTime> dFechaFinal { get; set; }
        public Nullable<decimal> dMontoPresupuesto { get; set; }
        public Nullable<decimal> dMontoReal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_UNION_DETALLE_PRESUPUESTO> T_UNION_DETALLE_PRESUPUESTO { get; set; }
    }
}
