//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioDetPresupuesto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioDetPresupuesto.IServicioDetPresupuesto")]
    public interface IServicioDetPresupuesto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetPresupuesto/obtenerDetPresPorFechaYCatalogo", ReplyAction="http://tempuri.org/IServicioDetPresupuesto/obtenerDetPresPorFechaYCatalogoRespons" +
            "e")]
        MB.WCF.DataContract.DCDetallePresupuesto obtenerDetPresPorFechaYCatalogo(System.DateTime fecha, int idCatalogo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioDetPresupuesto/obtenerDetPresPorFechaYCatalogo", ReplyAction="http://tempuri.org/IServicioDetPresupuesto/obtenerDetPresPorFechaYCatalogoRespons" +
            "e")]
        System.Threading.Tasks.Task<MB.WCF.DataContract.DCDetallePresupuesto> obtenerDetPresPorFechaYCatalogoAsync(System.DateTime fecha, int idCatalogo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioDetPresupuestoChannel : MB.WEB.ServicioDetPresupuesto.IServicioDetPresupuesto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioDetPresupuestoClient : System.ServiceModel.ClientBase<MB.WEB.ServicioDetPresupuesto.IServicioDetPresupuesto>, MB.WEB.ServicioDetPresupuesto.IServicioDetPresupuesto {
        
        public ServicioDetPresupuestoClient() {
        }
        
        public ServicioDetPresupuestoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioDetPresupuestoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDetPresupuestoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioDetPresupuestoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MB.WCF.DataContract.DCDetallePresupuesto obtenerDetPresPorFechaYCatalogo(System.DateTime fecha, int idCatalogo) {
            return base.Channel.obtenerDetPresPorFechaYCatalogo(fecha, idCatalogo);
        }
        
        public System.Threading.Tasks.Task<MB.WCF.DataContract.DCDetallePresupuesto> obtenerDetPresPorFechaYCatalogoAsync(System.DateTime fecha, int idCatalogo) {
            return base.Channel.obtenerDetPresPorFechaYCatalogoAsync(fecha, idCatalogo);
        }
    }
}
