//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioHisTipoCambio {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioHisTipoCambio.IServicioHisTipoCambio")]
    public interface IServicioHisTipoCambio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHisTipoCambio/registroTipoCambio", ReplyAction="http://tempuri.org/IServicioHisTipoCambio/registroTipoCambioResponse")]
        void registroTipoCambio(MB.WCF.DataContract.DCHisTipoCambio dcHisTipoCambio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioHisTipoCambio/registroTipoCambio", ReplyAction="http://tempuri.org/IServicioHisTipoCambio/registroTipoCambioResponse")]
        System.Threading.Tasks.Task registroTipoCambioAsync(MB.WCF.DataContract.DCHisTipoCambio dcHisTipoCambio);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioHisTipoCambioChannel : MB.WEB.ServicioHisTipoCambio.IServicioHisTipoCambio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioHisTipoCambioClient : System.ServiceModel.ClientBase<MB.WEB.ServicioHisTipoCambio.IServicioHisTipoCambio>, MB.WEB.ServicioHisTipoCambio.IServicioHisTipoCambio {
        
        public ServicioHisTipoCambioClient() {
        }
        
        public ServicioHisTipoCambioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioHisTipoCambioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHisTipoCambioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioHisTipoCambioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void registroTipoCambio(MB.WCF.DataContract.DCHisTipoCambio dcHisTipoCambio) {
            base.Channel.registroTipoCambio(dcHisTipoCambio);
        }
        
        public System.Threading.Tasks.Task registroTipoCambioAsync(MB.WCF.DataContract.DCHisTipoCambio dcHisTipoCambio) {
            return base.Channel.registroTipoCambioAsync(dcHisTipoCambio);
        }
    }
}
