//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioCategorias {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCategorias.IServicioCategorias")]
    public interface IServicioCategorias {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCategorias/ObtenerCategorias", ReplyAction="http://tempuri.org/IServicioCategorias/ObtenerCategoriasResponse")]
        MB.WCF.DataContract.DCCategorias[] ObtenerCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCategorias/ObtenerCategorias", ReplyAction="http://tempuri.org/IServicioCategorias/ObtenerCategoriasResponse")]
        System.Threading.Tasks.Task<MB.WCF.DataContract.DCCategorias[]> ObtenerCategoriasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCategoriasChannel : MB.WEB.ServicioCategorias.IServicioCategorias, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCategoriasClient : System.ServiceModel.ClientBase<MB.WEB.ServicioCategorias.IServicioCategorias>, MB.WEB.ServicioCategorias.IServicioCategorias {
        
        public ServicioCategoriasClient() {
        }
        
        public ServicioCategoriasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCategoriasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCategoriasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCategoriasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MB.WCF.DataContract.DCCategorias[] ObtenerCategorias() {
            return base.Channel.ObtenerCategorias();
        }
        
        public System.Threading.Tasks.Task<MB.WCF.DataContract.DCCategorias[]> ObtenerCategoriasAsync() {
            return base.Channel.ObtenerCategoriasAsync();
        }
    }
}
