//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.WEB.ServicioGastos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioGastos.IServicioGastos")]
    public interface IServicioGastos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGastos/guardarGasto", ReplyAction="http://tempuri.org/IServicioGastos/guardarGastoResponse")]
        bool guardarGasto(MB.WCF.DataContract.DCGastos gastos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGastos/guardarGasto", ReplyAction="http://tempuri.org/IServicioGastos/guardarGastoResponse")]
        System.Threading.Tasks.Task<bool> guardarGastoAsync(MB.WCF.DataContract.DCGastos gastos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGastos/obtenerUltimoGasto", ReplyAction="http://tempuri.org/IServicioGastos/obtenerUltimoGastoResponse")]
        MB.WCF.DataContract.DCGastos obtenerUltimoGasto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioGastos/obtenerUltimoGasto", ReplyAction="http://tempuri.org/IServicioGastos/obtenerUltimoGastoResponse")]
        System.Threading.Tasks.Task<MB.WCF.DataContract.DCGastos> obtenerUltimoGastoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioGastosChannel : MB.WEB.ServicioGastos.IServicioGastos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioGastosClient : System.ServiceModel.ClientBase<MB.WEB.ServicioGastos.IServicioGastos>, MB.WEB.ServicioGastos.IServicioGastos {
        
        public ServicioGastosClient() {
        }
        
        public ServicioGastosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioGastosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGastosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioGastosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool guardarGasto(MB.WCF.DataContract.DCGastos gastos) {
            return base.Channel.guardarGasto(gastos);
        }
        
        public System.Threading.Tasks.Task<bool> guardarGastoAsync(MB.WCF.DataContract.DCGastos gastos) {
            return base.Channel.guardarGastoAsync(gastos);
        }
        
        public MB.WCF.DataContract.DCGastos obtenerUltimoGasto() {
            return base.Channel.obtenerUltimoGasto();
        }
        
        public System.Threading.Tasks.Task<MB.WCF.DataContract.DCGastos> obtenerUltimoGastoAsync() {
            return base.Channel.obtenerUltimoGastoAsync();
        }
    }
}
